# se basa en una imagen
FROM python:3.7.0-alpine


# nuevo
# instalando dependencias
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

# establecemos el directorio de trabajo
WORKDIR /usr/src/app

# añadiendo e instalando requerimientos
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# nuevo
# agregando entripoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# copiamos app
COPY . /usr/src/app

# ejecutando el server
#CMD python manage.py run -h 0.0.0.0
CMD ["/usr/src/app/entrypoint.sh"]

